### ISSUE TITLE
Incorrect font color on buttons and links for Iphone

### ISSUE THREAD

**Issue by thedonutdan** [cse110-sp24-group4/cse110-sp24-group4#133]
**Describe the bug**
The font color is showing up as standard blue for unclicked links and purple for clicked links on my Iphone
The font color for buttons is showing up as blue
Some links in the header are showing up correctly such as "launch in browser" and "view by date"

**To Reproduce**
1. Navigate to site on Iphone
2. PWA acts in the same manner

**Expected behavior**
The color should follow the same font color as on desktop (dark green).

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS16.3.1
 - Browser: Safari
 - Version: Uknown (thanks Apple)
 
**Additional context**
Safari uses webkit which may impact the styling of fonts. I'll post any information I figure out about this specific issue as additional comments

**Comment by thedonutdan** [comment]
I believe I found the problem. The font color seems to not have been set at all. This will default to black on some browsers but blue on webkit. I've gone ahead and set a rule that sets all button's colors to the font color, with the exception of the notes-overflow-button which is set to black to be consistent with the text of the note. This issue can be closed when it is verified the problem is solved upon deployment

**Comment by thedonutdan** [comment]
Tentatively fixed

**Comment by mattqgoldberg** [comment]
Fixed

**Comment by thedonutdan** [comment]
Most are fixed, I am still having this bug for the home button when I am on the project page of the mobile site in browser. The rule is in the CSS and the same for both pages but for some reason it isn't applying to the project page

**Comment by mattqgoldberg** [comment]
It looks fine on mine maybe clear cache?

**Comment by thedonutdan** [comment]
Clearing the cache fixed issues with PWA on my iphone 11
