### ISSUE TITLE
Title Input box extends past note block on IPhone 11

### ISSUE THREAD

**Issue by thedonutdan** [cse110-sp24-group4/cse110-sp24-group4#135]
**Describe the bug**
When editing a note, the title input box hangs off the right-hand side of the note block instead of staying contained within it. 

**To Reproduce**
1. Go to Projects
2. Select a project
3. Select "new note"
4. Select "edit"
5. Title input box hangs off the edge

**Expected behavior**
All elements of the notes should remain within the bounds of the noteblock.

Device: iPhone11
OS: iOS16.3.1
Browser: Safari
Version: Uknown (thanks Apple)

**Additional context**
I suspect we may be setting an absolute value in pixels for the size of the input box. Instead we should be using some relative measurement such as a percentage

**Comment by mattqgoldberg** [comment]
Fixed with latest release on my iphone
