### ISSUE TITLE
Implement Project Roadmap

### ISSUE THREAD

**Issue by thedonutdan** [cse110-sp24-group4/cse110-sp24-group4#22]

**Comment by thedonutdan** [comment]
I'm trying to set up a roadmap for DevDog through Github projects. The board style is set up, but the roadmap template escapes my understanding. Anyone with experience with GitHub projects is welcome to take a look at this and help out

**Comment by mattqgoldberg** [comment]
Roadmaps seem to be setting dates for specific due dates that a Github issue should be completed. Not sure if we need can be that specific, although I can see it being useful for certain issues that need to be finished at a specific time. I did create a Github Milestone that groups issues that we need to complete by tomorrow to finish our MVP

**Comment by thedonutdan** [comment]
there are some class-defined hard deadlines, like June 7th for final product, June 11th for demo so we can implement that. The rest of the deadlines are up to us to set. Akshay did recommend using GitHub projects for roadmapping, so this is an issue we need to resolve

**Comment by mattqgoldberg** [comment]
No
