### ISSUE TITLE
check validity of project naming

### ISSUE THREAD

**Issue by thedonutdan** [cse110-sp24-group4/cse110-sp24-group4#34]
Currently there are no restrictions on project names. It may be prudent to add the following rules:
- Restrict duplicate naming (medium importance - duplicate project names will just make multiple links to the same project)
- Certain characters could affect the behavior of the URL parameter. More research needed. (high importance - could break the project page entirely with little feedback for user)

**Comment by thedonutdan** [comment]
After some research it looks like we can utilize the `encodeURIComponent()` and `decodeURIComponent()` functions to automatically add and remove the proper escape sequences for our params.

**Comment by thedonutdan** [comment]
Useful resource is [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) which enumerates reserved characters for URIs.

**Comment by mattqgoldberg** [comment]
Related bug also, if you create a project with a blank name, you cannot delete it from the list. Should be fixed if we check for empty string.
