### ISSUE TITLE
Filename inconsistencies

### ISSUE THREAD

**Issue by mattqgoldberg** [cse110-sp24-group4/cse110-sp24-group4#37]
index.html should go in the pages folder?
Rename html files
Suggested names:
index.html -> home.html
landing.html -> projects.html
project.html -> notes.html

**Comment by thedonutdan** [comment]
index.html should stay in the root folder as it is convention for webpage design, as well as the name index.html itself for the entry point.

**Comment by thedonutdan** [comment]
renamed other files and adjusted paths for clarity per guidelines
