### ISSUE TITLE
Start page formatting

### ISSUE THREAD

**Issue by mattqgoldberg** [cse110-sp24-group4/cse110-sp24-group4#38]
index.html has an unnecessary horizontal scroll bar
Text at the very top of the screen is cut off

**Comment by thedonutdan** [comment]
Just to be sure since it renders correctly in my browser, by text at the top of the screen do you mean the header? Also please identify the specific browser where this bug is occurring.

**Comment by mattqgoldberg** [comment]
Horizontal scroll bar is present on chrome on nearly all devices I tried, the cut off text I need to investigate further it seems to only be broken on my screen (1920x1200), but when I try to emulate my display using chrome devTools it renders property so I'm not sure what the issue is

**Comment by mattqgoldberg** [comment]
Fixed at some point idk
