### ISSUE TITLE
Landing.js Unit Tests

### ISSUE THREAD

**Issue by mattqgoldberg** [cse110-sp24-group4/cse110-sp24-group4#43]
Create a landing.unit.js file to test the functionality of functions in landing.js
Try to consider all edge cases

**Comment by thedonutdan** [comment]
**NAME CHANGE**
landing.js->project.js

**Comment by gauthamp123** [comment]
For tests:
1. Test that project button creates a project
2. Test that a dummy project saves in local storage
3. Test that project with no name do not get added
4. Test that project properly deletes from both local storage and the webpage
5. Test that projects with same name doesnt get added?

Can someone check this and see if I should add any tests and if we want test number 5?

**Comment by thedonutdan** [comment]
I'm going to be handling the name checks for projects and writing tests for that so I can take care of implementing these unit tests at the same time
