### ISSUE TITLE
sort notes by most recent

### ISSUE THREAD

**Issue by thedonutdan** [cse110-sp24-group4/cse110-sp24-group4#48]
When displayed, notes should be sorted by most recent date, whether we are viewing a specific project or if we are searching by date. We will have to identify a way to associate dates with notes and sort accordingly.

**Comment by Kekoa-Pickett** [comment]
Are we sorting by date modified or date created? Also, am I sorting the notes and/or the projects? If we are sorting by notes, are we sorting the notes in each project page or are we creating a new page with all notes from all projects together that I am sorting? 

Right now, I have gotten the date created to show up and store in the local storage.

**Comment by thedonutdan** [comment]
Notes is the focus here. Date created, so that when you select a specific project it starts with the most recent note created, a timestamp would probably be useful too since we could create multiple notes in a day.
Since the notes are stored as objects, we should be able to just add a date property, from there we can sort the array by date. You just have to provide the custom comparator for the sort function
Something like:
```
function sortByDateTime(entries) {
    return notes.sort((a, b) => a.dateTime - b.dateTime);
}
```
If you want specific help with the implementation I can take a look at your code, or we can hop on a call and discuss more details

**Comment by Kekoa-Pickett** [comment]
Ok I should be able to do that, thanks! I'll let you know if need help.
