### ISSUE TITLE
Blank or duplicate named projects are not properly deleted

### ISSUE THREAD

**Issue by Kekoa-Pickett** [cse110-sp24-group4/cse110-sp24-group4#79]
Blank projects and duplicate name projects create issues for the id. Blank projects can't be deleted since they have no id to delete, and deleting a duplicate name gets rid of both in storage since they have the same id.

**Comment by Kekoa-Pickett** [comment]
2 options I thought of:

1. Like google docs and other sites, make sure the user doesn't input either a blank or an already used project name.
2. I see is making it the same way as our notes section where we create a random ID for each project.

I would recommend the first one so our user can tell which folder is which rather than searching through duplicates.

**Comment by thedonutdan** [comment]
This issue will be addressed in #34
