### ISSUE TITLE
Generate new notes for completed todo list items

### ISSUE THREAD

**Issue by thedonutdan** [cse110-sp24-group4/cse110-sp24-group4#95]
To make the todo list more useful, we should include an option to mark items as done, then upon clicking a button a user may prompt them to be turned into new notes and removed from the todo list. The todo item would be the title and the user may enter notes in the appropriate section.

**Comment by Kekoa-Pickett** [comment]
Should I new note's time be the time the task was created or time the note was created?

**Comment by thedonutdan** [comment]
Time the note was created I think would be good.
